version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: medipack-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medivault
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: medipack-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=medivault
      - USE_MOCK_S3=true
      - JWT_SECRET_KEY=replace_with_a_strong_random_secret_at_least_32_chars_123456
      - ENCRYPTION_KEY=fearvzStwhCfiCaafOMMQdx211nzsfIuEpgyrvKlWGI=
      - CORS_ALLOW_ORIGINS=http://localhost,http://localhost:80
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medipack-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
